### ISSUE TITLE
As a user, I want my account to be stored if I log in

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs48-w20/4pm-laptops-comparer#21]
When I login and get a JWT from front end I expect
- [x] Database to have the user info stored in it

**Comment by jayleenli** [comment]
I have a basic idea structure for how things will be stored in the MongoDB

- [ ] db = client.user_info
- [ ] db["users"]
` {
User_Google_id : Comparison_Id
}`
- [ ]  db["user_comparisons"]
{
Comparison_Id: [id, id, id, id]
}
Another db for laptop info
- [ ] db = client.products
- [ ] db["laptop_info"]
{
Laptop_id : 12345
....(any other key value pairs based on what is webscraped)...
}

**Comment by aeshapar** [comment]
Modifications to a workspace, as well as additions of new workspaces, are reflected upon logging out and logging back in.
