### ISSUE TITLE
As a user I want price information and other laptop information to be retrieved automatically (web scraping)

### ISSUE THREAD

**Issue by jayleenli** [ucsb-cs48-w20/4pm-laptops-comparer#22]
When given an amazon link I expect to have information about the product stored in the database

- [x] given a link, a dictionary of information about the laptop is created
- [x] laptop information (in the dict) get stored in database in the products db under laptop_info collection

Acceptance Criteria: 
Given a link of amazon laptop, there is an endpoint created where the front end can call that will webscrape for the information

**Comment by jayleenli** [comment]
I found an article here I don't know if it will help you guys! https://www.scrapehero.com/tutorial-how-to-scrape-amazon-product-details-using-python-and-selectorlib/

**Comment by tonysun9** [comment]
Made a quick prototype! https://github.com/ucsb-cs48-w20/4pm-laptops-comparer/tree/tony

**Comment by aeshapar** [comment]
Price information from Amazon displays along with the product name.
